// <auto-generated />
using System;
using CRUD_using_MySQL_web_mvc_netcore6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_using_MySQL_web_mvc_netcore6.Migrations
{
    [DbContext(typeof(HealthCareDbContext))]
    partial class HealthCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CRUD_using_MySQL_web_mvc_netcore6.Models.PatientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int?>("AssignedDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("FristName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<int?>("PhysicianDoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Schedule")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PhysicianDoctorId");

                    b.ToTable("PatientModel");
                });

            modelBuilder.Entity("CRUD_using_MySQL_web_mvc_netcore6.Models.PhysicianModel", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DoctorFirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorLastName")
                        .HasColumnType("longtext");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("PhysicianModel");
                });

            modelBuilder.Entity("CRUD_using_MySQL_web_mvc_netcore6.Models.SpecializationModel", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("SpecializationId");

                    b.ToTable("SpecializationModel");
                });

            modelBuilder.Entity("CRUD_using_MySQL_web_mvc_netcore6.Models.PatientModel", b =>
                {
                    b.HasOne("CRUD_using_MySQL_web_mvc_netcore6.Models.PhysicianModel", "Physician")
                        .WithMany("PatientModel")
                        .HasForeignKey("PhysicianDoctorId");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("CRUD_using_MySQL_web_mvc_netcore6.Models.PhysicianModel", b =>
                {
                    b.HasOne("CRUD_using_MySQL_web_mvc_netcore6.Models.SpecializationModel", "Specialization")
                        .WithMany("PhysicianModel")
                        .HasForeignKey("SpecializationId");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("CRUD_using_MySQL_web_mvc_netcore6.Models.PhysicianModel", b =>
                {
                    b.Navigation("PatientModel");
                });

            modelBuilder.Entity("CRUD_using_MySQL_web_mvc_netcore6.Models.SpecializationModel", b =>
                {
                    b.Navigation("PhysicianModel");
                });
#pragma warning restore 612, 618
        }
    }
}
